apiVersion: v1
kind: ConfigMap
metadata:
  name: olive-lifecycle-frontend-config
  namespace: agrotrack-frontend
data:
  REACT_APP_API_URL: "https://api.agrotrack.conceptatlas.eu"
  REACT_APP_SHOW_DEMO_LOGIN: "true"
