apiVersion: v1
kind: ConfigMap
metadata:
  name: olive-lifecycle-frontend-config
  namespace: agrotrack-frontend
data:
  REACT_APP_API_URL: "http://185.193.66.50:31847"
  REACT_APP_SHOW_DEMO_LOGIN: "true"
