apiVersion: v1
kind: ConfigMap
metadata:
  name: olive-lifecycle-frontend-config
  namespace: oleachron-frontend
data:
  REACT_APP_API_URL: "https://api.oleachron.conceptatlas.eu"
  REACT_APP_SHOW_DEMO_LOGIN: "true"
