import { StyleSheet } from 'react-native';
import type { AppColors } from '../../theme';
import { createElevation, radii, spacing, typography } from '../../theme';

/** Shared My Oil visual tokens — mirrors web MyOilPage.css + Money paper islands. */
export function createMyOilStyles(colors: AppColors, tapMin: number) {
  const paper = {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderLight,
    ...createElevation(colors, 'sm'),
  } as const;

  return StyleSheet.create({
    gap: { gap: spacing.md },
    center: { paddingTop: 40, gap: 8 },
    overviewGrid: {
      gap: spacing.md,
      marginTop: spacing.md,
    },
    overviewGridLower: {
      marginTop: spacing.lg,
      marginBottom: spacing.md,
      gap: spacing.md,
    },

    header: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    title: {
      ...typography.styles.h1,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700',
      letterSpacing: -0.4,
      color: colors.textPrimary,
      flexShrink: 1,
    },
    seasonBadge: {
      paddingVertical: spacing.sm,
      paddingHorizontal: spacing.md,
      borderRadius: radii.lg,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    seasonText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.primary,
    },

    activity: {
      borderRadius: radii.card,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      padding: spacing.md,
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    activityTitle: {
      ...typography.styles.overline,
      fontSize: 11,
      letterSpacing: 0.6,
      color: colors.textTertiary,
    },
    activityRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    activityPill: {
      flexGrow: 1,
      flexBasis: '45%',
      minWidth: 140,
      flexDirection: 'row',
      gap: spacing.sm,
      alignItems: 'flex-start',
      paddingVertical: spacing.sm + 2,
      paddingHorizontal: spacing.sm + 2,
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      ...createElevation(colors, 'flat'),
    },
    activityIconWell: {
      width: 28,
      height: 28,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    activityLabel: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: colors.textTertiary,
      marginBottom: 2,
    },
    activityValue: {
      fontSize: 12.5,
      fontWeight: '650' as '600',
      lineHeight: 16,
      color: colors.textPrimary,
    },

    tabsSticky: {
      marginBottom: spacing.sm,
    },
    tabs: {
      flexDirection: 'row',
      gap: 4,
      paddingVertical: 4,
    },
    tabBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderRadius: radii.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
      minHeight: Math.min(tapMin, 40),
    },
    tabBtnOn: {
      backgroundColor: colors.surface,
      borderColor: colors.oliveBorder,
      ...createElevation(colors, 'sm'),
    },
    tabLabel: {
      fontSize: 12.5,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
      textAlign: 'center',
    },
    tabLabelOn: {
      color: colors.textPrimary,
      fontWeight: '700',
    },

    heroCompact: {
      borderRadius: radii.dock,
      ...paper,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.base,
      gap: 6,
      marginBottom: spacing.sm,
    },
    heroTotal: {
      fontSize: 34,
      fontWeight: '800',
      lineHeight: 38,
      letterSpacing: -0.8,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    heroPackLine: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
      lineHeight: 20,
    },
    heroStatusRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: spacing.sm,
    },
    heroStatusCard: {
      flex: 1,
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      paddingVertical: 10,
      paddingHorizontal: 10,
      gap: 4,
    },
    heroStatusLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    heroStatusLabelText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.3,
      color: colors.textTertiary,
    },
    heroStatusValue: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    stockGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    stockCard: {
      flex: 1,
      borderRadius: radii.lg,
      ...paper,
      padding: spacing.md,
      gap: 2,
    },
    stockCardLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    stockCardValue: {
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.5,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    stockCardMeta: {
      fontSize: 13,
      color: colors.textTertiary,
    },
    stockCardHeld: {
      marginTop: 4,
      fontSize: 12,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    attentionClear: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 4,
    },
    attentionClearText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    attentionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 4,
    },
    lotCardCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      minHeight: 112,
    },
    lotTotal: {
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    holdCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
    },
    menuBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },

    hero: {
      borderRadius: radii.dock,
      ...paper,
      padding: spacing.lg,
      gap: spacing.md,
      overflow: 'hidden',
      marginBottom: spacing.sm,
    },
    heroWash: {
      position: 'absolute',
      top: -40,
      right: -30,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: colors.primaryLight,
      opacity: 0.85,
    },
    heroWashSoft: {
      position: 'absolute',
      bottom: -50,
      left: -20,
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: colors.primaryLight,
      opacity: 0.45,
    },
    heroTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.md,
      zIndex: 1,
    },
    heroMain: { flex: 1, minWidth: 0 },
    heroEyebrow: {
      ...typography.styles.overline,
      fontSize: 12,
      letterSpacing: 0.6,
      color: colors.textTertiary,
    },
    heroQty: {
      marginTop: 6,
      fontSize: 28,
      fontWeight: '700',
      lineHeight: 32,
      letterSpacing: -0.5,
      color: colors.textPrimary,
    },
    heroApprox: {
      marginTop: 4,
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    heroArt: {
      opacity: 0.32,
      marginTop: 4,
    },
    heroChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: spacing.md,
    },
    chip: {
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: radii.full,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    chipText: {
      fontSize: 12,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    chipFilter: {
      flexGrow: 0,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: radii.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      minHeight: Math.min(tapMin, 36),
      justifyContent: 'center',
    },
    chipFilterOn: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.primary,
    },
    chipFilterText: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    chipFilterTextOn: {
      color: colors.textPrimary,
    },
    chipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: spacing.sm,
    },

    heroSplit: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      zIndex: 1,
    },
    heroBlock: {
      flexGrow: 1,
      flexBasis: '30%',
      minWidth: 100,
      borderRadius: radii.lg,
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    heroBlockWarehouse: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
    },
    heroBlockHome: {
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.borderLight,
    },
    heroBlockHomeOn: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
    },
    heroSplitLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 4,
    },
    heroSplitLabelText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },
    heroSplitValue: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },

    quick: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.sm,
      zIndex: 1,
    },
    quickMoreWrap: {
      position: 'relative',
    },
    overflowMenu: {
      minWidth: 220,
      backgroundColor: colors.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: radii.lg,
      padding: 6,
      zIndex: 30,
      ...createElevation(colors, 'floating'),
    },
    overflowItem: {
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: radii.sm,
      minHeight: tapMin,
      justifyContent: 'center',
    },
    overflowItemText: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },

    sectionHead: {
      marginBottom: spacing.md,
      gap: 4,
    },
    sectionTitle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    sectionTitleText: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },
    sectionIntro: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },

    panel: {
      borderRadius: radii.card,
      ...paper,
      padding: spacing.lg,
      gap: spacing.sm,
    },
    panelAction: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
      ...createElevation(colors, 'raised'),
    },
    panelCalm: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
    },
    panelHousehold: {
      backgroundColor: colors.surface,
    },

    householdBanner: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'baseline',
      gap: 6,
      marginBottom: spacing.md,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: radii.lg,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    householdBannerQty: {
      fontSize: 17,
      fontWeight: '700',
      letterSpacing: -0.2,
      color: colors.textPrimary,
    },
    householdBannerNote: {
      fontSize: 12.5,
      color: colors.textTertiary,
    },
    householdBits: {
      gap: 8,
      marginBottom: spacing.sm,
    },
    householdBit: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      gap: spacing.sm,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: radii.md,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    householdBitLabel: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    householdBitValue: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },

    empty: { gap: 8, alignItems: 'flex-start' },
    emptyTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    emptyBody: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
    },

    inv: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    invCard: {
      flexGrow: 1,
      flexBasis: '30%',
      minWidth: 110,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      borderRadius: radii.lg,
      backgroundColor: colors.surfaceMuted,
      padding: spacing.md,
      gap: 4,
    },
    invCardIconWell: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
      marginBottom: 4,
    },
    invCardLabel: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    invCardValue: {
      fontSize: 22,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.textPrimary,
    },
    invCardMeta: {
      fontSize: 12.5,
      color: colors.textTertiary,
    },

    meter: {
      flexDirection: 'row',
      height: 5,
      borderRadius: radii.full,
      overflow: 'hidden',
      backgroundColor: colors.borderLight,
      marginTop: 10,
    },
    meterAvail: {
      height: '100%',
      backgroundColor: colors.primary,
    },
    meterHeld: {
      height: '100%',
      backgroundColor: colors.accentGold,
      opacity: 0.7,
    },

    waiting: { gap: spacing.sm },
    waitingItem: {
      gap: 4,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      ...createElevation(colors, 'flat'),
    },
    waitingName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    waitingPack: {
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    waitingStory: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    waitingActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.sm,
      marginTop: 10,
    },

    stepper: { gap: 10, marginBottom: spacing.sm },
    stepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: radii.md,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    stepperLabel: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    stepperControls: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    stepperBtn: {
      width: Math.max(40, tapMin * 0.75),
      height: Math.max(40, tapMin * 0.75),
      borderRadius: radii.control,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperBtnDisabled: { opacity: 0.4 },
    stepperValue: {
      minWidth: 28,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },

    toggle: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    toggleBtn: {
      flexGrow: 1,
      minWidth: 100,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      borderRadius: radii.control,
      paddingVertical: 12,
      paddingHorizontal: 10,
      alignItems: 'center',
      minHeight: tapMin,
      justifyContent: 'center',
    },
    toggleBtnOn: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    toggleBtnText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    toggleBtnTextOn: {
      color: colors.textPrimary,
      fontWeight: '700',
    },

    field: { gap: 6, marginBottom: 14 },
    fieldLabel: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    fieldInput: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      color: colors.textPrimary,
      borderRadius: radii.control,
      paddingVertical: 12,
      paddingHorizontal: 12,
      fontSize: 16,
      minHeight: tapMin,
    },
    checkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
      minHeight: tapMin,
    },
    checkBox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    checkBoxOn: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },

    flow: { gap: 4 },
    flowStep: {
      marginTop: spacing.md,
      marginBottom: spacing.sm,
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    flowStepFirst: { marginTop: 0 },
    flowQty: {
      fontSize: 24,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.textPrimary,
    },
    flowTotal: {
      marginTop: spacing.sm,
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    flowHint: {
      marginTop: 4,
      fontSize: 13,
      color: colors.textTertiary,
    },
    flowListItem: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 4,
    },
    giveError: {
      marginTop: 12,
      color: colors.error,
      fontSize: 14,
    },

    sourceList: { gap: 8, marginBottom: spacing.sm },
    sourceCard: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'flex-start',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      borderRadius: radii.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    sourceCardOn: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    sourceCardSummary: {
      marginBottom: spacing.sm,
    },
    sourceCardIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sourceCardBody: { flex: 1, minWidth: 0, gap: 2 },
    sourceCardTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    sourceCardSub: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    sourceCardMeta: {
      fontSize: 12.5,
      color: colors.textTertiary,
      marginTop: 2,
    },

    timeline: { gap: spacing.sm },
    timelineDay: {
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      padding: spacing.md,
      gap: spacing.sm,
    },
    timelineLabel: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: colors.textTertiary,
      marginBottom: 4,
    },
    timelineItem: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'flex-start',
      paddingTop: spacing.sm,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.borderLight,
    },
    timelineItemFirst: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    timelineBadge: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    timelineBody: { flex: 1, minWidth: 0 },
    timelineRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      gap: spacing.sm,
    },
    timelineAction: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
      flex: 1,
    },
    timelineDetail: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 2,
    },
    timelineDeltaPlus: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.success,
    },
    timelineDeltaMinus: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.error,
    },

    lotList: { gap: spacing.sm },
    lotCard: {
      position: 'relative',
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
      padding: spacing.md,
      gap: 4,
      overflow: 'hidden',
      ...createElevation(colors, 'flat'),
    },
    lotCardArt: {
      position: 'absolute',
      top: 12,
      right: 14,
      opacity: 0.22,
    },
    lotWhen: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
      paddingRight: 48,
    },
    lotWhere: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    lotMore: {
      color: colors.textTertiary,
    },
    lotPack: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
      marginTop: 4,
    },
    lotMeta: {
      fontSize: 13,
      color: colors.textTertiary,
    },
    lotActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginTop: 10,
    },
    lotDetailLinks: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      marginTop: spacing.lg,
    },

    linkish: {
      marginTop: 10,
      paddingVertical: 4,
    },
    linkishText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.primary,
    },

    stickyCta: {
      position: 'absolute',
      left: 12,
      right: 12,
      bottom: 12,
      zIndex: 40,
      borderRadius: radii.xl,
      padding: spacing.sm,
      backgroundColor: colors.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      ...createElevation(colors, 'floating'),
    },

    footerRow: {
      flexDirection: 'row',
      gap: spacing.sm,
    },
    btnPrimary: {
      flex: 1,
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    btnPrimaryDisabled: {
      backgroundColor: colors.gray300,
    },
    btnPrimaryText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.onOlive,
    },
    btnSecondary: {
      flex: 1,
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    btnSecondaryText: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    btnGhost: {
      minHeight: Math.min(tapMin, 40),
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: radii.lg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnGhostText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    btnSm: {
      flexGrow: 0,
      flexBasis: 'auto',
      paddingHorizontal: 14,
      minWidth: 0,
    },

    buyerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: radii.lg,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      minHeight: tapMin,
    },
    buyerChipCopy: { flex: 1, minWidth: 0 },
    buyerChipName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    buyerChange: {
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    buyerChangeText: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.primary,
    },
    buyerClear: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    buyerHint: {
      fontSize: 13,
      color: colors.textTertiary,
      marginBottom: 6,
    },
    buyerList: {
      gap: 4,
      marginVertical: 8,
      maxHeight: 180,
    },
    buyerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: radii.md,
      backgroundColor: colors.surfaceMuted,
      minHeight: Math.min(tapMin, 44),
    },
    buyerRowName: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    buyerRowMeta: {
      fontSize: 12,
      color: colors.textTertiary,
    },
  });
}

export type MyOilStyles = ReturnType<typeof createMyOilStyles>;
