import { StyleSheet } from 'react-native';
import type { AppColors } from '../../theme';
import { createElevation, radii, spacing, typography } from '../../theme';

/** Shared My Oil visual tokens — mirrors web MyOilPage.css + Money paper islands. */
export function createMyOilStyles(colors: AppColors, tapMin: number) {
  const paper = {
    backgroundColor: colors.surface,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: colors.borderLight,
    ...createElevation(colors, 'sm'),
  } as const;

  return StyleSheet.create({
    gap: { gap: spacing.md },
    center: { paddingTop: 40, gap: 8 },
    overviewGrid: {
      gap: spacing.md,
      marginTop: spacing.md,
    },
    overviewGridLower: {
      marginTop: spacing.lg,
      marginBottom: spacing.md,
      gap: spacing.md,
    },

    header: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    pageTitle: {
      flex: 1,
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.4,
      color: colors.textPrimary,
    },
    headerSupport: {
      flex: 1,
      minWidth: 0,
    },
    title: {
      ...typography.styles.h1,
      fontSize: 28,
      lineHeight: 34,
      fontWeight: '700',
      letterSpacing: -0.4,
      color: colors.textPrimary,
      flexShrink: 1,
    },
    seasonBadge: {
      flexShrink: 1,
      maxWidth: '52%',
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: radii.full,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    seasonText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.primary,
    },

    activity: {
      borderRadius: radii.card,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      padding: spacing.md,
      gap: spacing.sm,
      marginBottom: spacing.md,
    },
    activityTitle: {
      ...typography.styles.overline,
      fontSize: 11,
      letterSpacing: 0.6,
      color: colors.textTertiary,
    },
    activityRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    activityPill: {
      flexGrow: 1,
      flexBasis: '45%',
      minWidth: 140,
      flexDirection: 'row',
      gap: spacing.sm,
      alignItems: 'flex-start',
      paddingVertical: spacing.sm + 2,
      paddingHorizontal: spacing.sm + 2,
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      ...createElevation(colors, 'flat'),
    },
    activityIconWell: {
      width: 28,
      height: 28,
      borderRadius: 9,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    activityLabel: {
      fontSize: 10,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: colors.textTertiary,
      marginBottom: 2,
    },
    activityValue: {
      fontSize: 12.5,
      fontWeight: '650' as '600',
      lineHeight: 16,
      color: colors.textPrimary,
    },

    tabsSticky: {
      marginBottom: spacing.sm,
    },
    tabs: {
      flexDirection: 'row',
      gap: 4,
      paddingVertical: 4,
    },
    tabBtn: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderRadius: radii.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: 'transparent',
      backgroundColor: 'transparent',
      minHeight: Math.min(tapMin, 40),
    },
    tabBtnRow: {
      flexDirection: 'row',
      gap: 5,
    },
    tabBtnOn: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
    },
    tabCount: {
      minWidth: 16,
      height: 16,
      paddingHorizontal: 4,
      borderRadius: 4,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: 'transparent',
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabCountText: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textSecondary,
      fontVariant: ['tabular-nums'],
    },
    tabLabel: {
      fontSize: 12.5,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
      textAlign: 'center',
    },
    tabLabelOn: {
      color: colors.textPrimary,
      fontWeight: '700',
    },

    heroCompact: {
      borderRadius: radii.dock,
      ...paper,
      paddingVertical: spacing.md,
      paddingHorizontal: spacing.base,
      gap: 6,
      marginBottom: spacing.sm,
    },
    heroTotal: {
      fontSize: 36,
      fontWeight: '700',
      lineHeight: 40,
      letterSpacing: -0.6,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    heroTotalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    heroCaption: {
      marginTop: -6,
      fontSize: 14,
      fontWeight: '500',
      color: colors.textSecondary,
    },
    heroPackLine: {
      fontSize: 16,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
      lineHeight: 21,
    },
    heroStatusRow: {
      flexDirection: 'row',
      gap: 8,
      marginTop: spacing.sm,
    },
    heroStatusCard: {
      flex: 1,
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      paddingVertical: 10,
      paddingHorizontal: 10,
      gap: 4,
    },
    heroStatusLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    heroStatusLabelText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.3,
      color: colors.textTertiary,
    },
    heroStatusValue: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    stockGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    stockHero: {
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 16,
      paddingHorizontal: 16,
      gap: 4,
      ...createElevation(colors, 'sm'),
    },
    stockEyebrow: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.1,
      textTransform: 'uppercase',
      color: colors.textSecondary,
    },
    stockHeroAmount: {
      fontSize: 34,
      fontWeight: '800',
      lineHeight: 40,
      letterSpacing: -0.8,
      color: colors.accentGold,
      fontVariant: ['tabular-nums'],
    },
    stockHeroPack: {
      marginTop: 2,
      fontSize: 16,
      fontWeight: '650' as '600',
      lineHeight: 21,
      color: colors.textPrimary,
    },
    stockHeroNote: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    stockCard: {
      flex: 1,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      padding: spacing.md,
      gap: 2,
      ...createElevation(colors, 'sm'),
    },
    stockCardLabel: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    stockCardValue: {
      fontSize: 28,
      fontWeight: '800',
      letterSpacing: -0.5,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    stockCardMeta: {
      fontSize: 13,
      color: colors.textTertiary,
    },
    stockCardHeld: {
      marginTop: 4,
      fontSize: 12,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    stockHeldPill: {
      alignSelf: 'flex-start',
      marginTop: 6,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: radii.full,
      backgroundColor: colors.eventExpenseSoft,
    },
    stockHeldText: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.eventExpense,
    },
    stockBulk: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: 18,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      paddingVertical: 12,
      paddingHorizontal: 14,
      ...createElevation(colors, 'sm'),
    },
    stockBulkIcon: {
      width: 36,
      height: 36,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.eventExpenseSoft,
    },
    stockBulkCopy: { flex: 1, minWidth: 0 },
    stockBulkValue: {
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
      color: colors.accentGold,
      fontVariant: ['tabular-nums'],
    },
    stockHome: {
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.oliveBorder,
      backgroundColor: colors.primaryLight,
      paddingVertical: 14,
      paddingHorizontal: 16,
      gap: 4,
    },
    stockHomeHead: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 4,
    },
    attentionClear: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingVertical: 4,
    },
    attentionClearText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    attentionCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 4,
    },
    lotCardCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      minHeight: 112,
    },
    lotTotal: {
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    holdCard: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: spacing.md,
      overflow: 'hidden',
    },
    holdCardUrgent: {
      borderColor: colors.oliveBorder,
      backgroundColor: colors.primaryLight,
    },
    holdUrgentMark: {
      position: 'absolute',
      left: 0,
      top: 10,
      bottom: 10,
      width: 3,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    holdCardBody: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    holdCardTop: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 10,
    },
    holdPack: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
      flexShrink: 0,
    },
    holdDeliver: {
      alignSelf: 'flex-start',
      marginTop: 8,
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: radii.md,
      backgroundColor: colors.primary,
    },
    holdDeliverText: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.onOlive,
    },
    menuBtn: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
    },

    hero: {
      borderRadius: radii.dock,
      ...paper,
      padding: spacing.lg,
      gap: spacing.md,
      overflow: 'hidden',
      marginBottom: spacing.sm,
    },
    heroWash: {
      position: 'absolute',
      top: -40,
      right: -30,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: colors.primaryLight,
      opacity: 0.85,
    },
    heroWashSoft: {
      position: 'absolute',
      bottom: -50,
      left: -20,
      width: 140,
      height: 140,
      borderRadius: 70,
      backgroundColor: colors.primaryLight,
      opacity: 0.45,
    },
    heroTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.md,
      zIndex: 1,
    },
    heroMain: { flex: 1, minWidth: 0 },
    heroQty: {
      marginTop: 6,
      fontSize: 28,
      fontWeight: '700',
      lineHeight: 32,
      letterSpacing: -0.5,
      color: colors.textPrimary,
    },
    heroApprox: {
      marginTop: 4,
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    heroArt: {
      opacity: 0.32,
      marginTop: 4,
    },
    heroChips: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginTop: spacing.md,
    },
    chip: {
      paddingVertical: 5,
      paddingHorizontal: 10,
      borderRadius: radii.full,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    chipText: {
      fontSize: 12,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    chipFilter: {
      flexGrow: 0,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: radii.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      minHeight: Math.min(tapMin, 36),
      justifyContent: 'center',
    },
    chipFilterOn: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.primary,
    },
    chipFilterText: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    chipFilterTextOn: {
      color: colors.textPrimary,
    },
    chipsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: spacing.sm,
    },

    heroSplit: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      zIndex: 1,
    },
    heroBlock: {
      flexGrow: 1,
      flexBasis: '30%',
      minWidth: 100,
      borderRadius: radii.lg,
      paddingVertical: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    heroBlockWarehouse: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
    },
    heroBlockHome: {
      backgroundColor: colors.surfaceMuted,
      borderColor: colors.borderLight,
    },
    heroBlockHomeOn: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
    },
    heroSplitLabel: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 4,
    },
    heroSplitLabelText: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },
    heroSplitValue: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },

    quick: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.sm,
      zIndex: 1,
    },
    quickMoreWrap: {
      position: 'relative',
    },
    overflowMenu: {
      minWidth: 220,
      backgroundColor: colors.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      borderRadius: radii.lg,
      padding: 6,
      zIndex: 30,
      ...createElevation(colors, 'floating'),
    },
    overflowItem: {
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: radii.sm,
      minHeight: tapMin,
      justifyContent: 'center',
    },
    overflowItemText: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },

    sectionHead: {
      marginBottom: spacing.md,
      gap: 4,
    },
    sectionTitle: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    sectionTitleText: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },
    sectionIntro: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },

    panel: {
      borderRadius: radii.card,
      ...paper,
      padding: spacing.lg,
      gap: spacing.sm,
    },
    panelAction: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
      ...createElevation(colors, 'raised'),
    },
    panelCalm: {
      backgroundColor: colors.primaryLight,
      borderColor: colors.oliveBorder,
    },
    panelHousehold: {
      backgroundColor: colors.surface,
    },

    householdBanner: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'baseline',
      gap: 6,
      marginBottom: spacing.md,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: radii.lg,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    householdBannerQty: {
      fontSize: 17,
      fontWeight: '700',
      letterSpacing: -0.2,
      color: colors.textPrimary,
    },
    householdBannerNote: {
      fontSize: 12.5,
      color: colors.textTertiary,
    },
    householdBits: {
      gap: 8,
      marginBottom: spacing.sm,
    },
    householdBit: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      gap: spacing.sm,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: radii.md,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    householdBitLabel: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    householdBitValue: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },

    empty: { gap: 8, alignItems: 'flex-start' },
    emptyTitle: {
      fontSize: 17,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    emptyBody: {
      fontSize: 14,
      lineHeight: 20,
      color: colors.textSecondary,
    },

    inv: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
    },
    invCard: {
      flexGrow: 1,
      flexBasis: '30%',
      minWidth: 110,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      borderRadius: radii.lg,
      backgroundColor: colors.surfaceMuted,
      padding: spacing.md,
      gap: 4,
    },
    invCardIconWell: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
      marginBottom: 4,
    },
    invCardLabel: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    invCardValue: {
      fontSize: 22,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.textPrimary,
    },
    invCardMeta: {
      fontSize: 12.5,
      color: colors.textTertiary,
    },

    meter: {
      flexDirection: 'row',
      height: 5,
      borderRadius: radii.full,
      overflow: 'hidden',
      backgroundColor: colors.borderLight,
      marginTop: 10,
    },
    meterAvail: {
      height: '100%',
      backgroundColor: colors.primary,
    },
    meterHeld: {
      height: '100%',
      backgroundColor: colors.accentGold,
      opacity: 0.7,
    },

    waiting: { gap: spacing.sm },
    waitingItem: {
      gap: 4,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      ...createElevation(colors, 'flat'),
    },
    waitingName: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    waitingPack: {
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    waitingStory: {
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    waitingActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: spacing.sm,
      marginTop: 10,
    },
    waitingTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: spacing.sm,
    },
    waitingMeta: {
      marginTop: 6,
      fontSize: 13,
      color: colors.textTertiary,
    },
    waitingMetaWarn: {
      color: colors.error,
      fontWeight: '650' as '600',
    },
    splitInputs: {
      marginTop: 10,
      gap: 2,
    },

    stepper: { gap: 10, marginBottom: spacing.sm },
    stepperRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: spacing.md,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: radii.md,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    stepperLabel: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    stepperControls: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    stepperBtn: {
      width: Math.max(40, tapMin * 0.75),
      height: Math.max(40, tapMin * 0.75),
      borderRadius: radii.control,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    stepperBtnDisabled: { opacity: 0.4 },
    stepperValue: {
      minWidth: 28,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    stepperInput: {
      minWidth: 44,
      paddingVertical: 4,
      paddingHorizontal: 4,
      textAlign: 'center',
      fontSize: 16,
      fontWeight: '700',
    },

    toggle: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginBottom: spacing.sm,
    },
    toggleBtn: {
      flexGrow: 1,
      minWidth: 100,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      borderRadius: radii.control,
      paddingVertical: 12,
      paddingHorizontal: 10,
      alignItems: 'center',
      minHeight: tapMin,
      justifyContent: 'center',
    },
    toggleBtnOn: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    toggleBtnText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    toggleBtnTextOn: {
      color: colors.textPrimary,
      fontWeight: '700',
    },

    field: { gap: 6, marginBottom: 14 },
    fieldLabel: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    fieldInput: {
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      color: colors.textPrimary,
      borderRadius: radii.control,
      paddingVertical: 12,
      paddingHorizontal: 12,
      fontSize: 16,
      minHeight: tapMin,
    },
    checkRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: spacing.sm,
      marginBottom: spacing.sm,
      minHeight: tapMin,
    },
    checkBox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1.5,
      borderColor: colors.border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    checkBoxOn: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },

    flow: { gap: 4 },
    flowStep: {
      marginTop: spacing.md,
      marginBottom: spacing.sm,
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    flowStepFirst: { marginTop: 0 },
    flowQty: {
      fontSize: 24,
      fontWeight: '700',
      letterSpacing: -0.3,
      color: colors.textPrimary,
    },
    flowTotal: {
      marginTop: spacing.sm,
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    flowHint: {
      marginTop: 4,
      fontSize: 13,
      color: colors.textTertiary,
    },
    flowListItem: {
      fontSize: 14,
      color: colors.textSecondary,
      marginTop: 4,
    },
    giveError: {
      marginTop: 12,
      color: colors.error,
      fontSize: 14,
    },

    pagerDots: {
      flexDirection: 'row',
      gap: 6,
      marginBottom: spacing.md,
    },
    pagerDot: {
      flex: 1,
      height: 5,
      borderRadius: radii.full,
      backgroundColor: colors.borderLight,
    },
    pagerDotDone: { backgroundColor: colors.oliveBorder },
    pagerDotOn: { flex: 1.6, backgroundColor: colors.primary },

    intentList: { gap: 8, marginBottom: spacing.sm },
    intentCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 12,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      borderRadius: radii.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
      minHeight: tapMin,
    },
    intentCardOn: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    intentIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    intentBody: { flex: 1, minWidth: 0, gap: 2 },
    intentTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    intentHint: {
      fontSize: 13,
      color: colors.textSecondary,
    },

    sourceList: { gap: 8, marginBottom: spacing.sm },
    sourceCard: {
      flexDirection: 'row',
      gap: 12,
      alignItems: 'flex-start',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surfaceMuted,
      borderRadius: radii.lg,
      paddingVertical: 12,
      paddingHorizontal: 14,
    },
    sourceCardOn: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    sourceCardSummary: {
      marginBottom: spacing.sm,
    },
    sourceCardIcon: {
      width: 34,
      height: 34,
      borderRadius: 11,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      alignItems: 'center',
      justifyContent: 'center',
    },
    sourceCardBody: { flex: 1, minWidth: 0, gap: 2 },
    sourceCardTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    sourceCardSub: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    sourceCardMeta: {
      fontSize: 12.5,
      color: colors.textTertiary,
      marginTop: 2,
    },

    timeline: { gap: spacing.sm },
    timelineDay: {
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surfaceMuted,
      padding: spacing.md,
      gap: spacing.sm,
    },
    timelineLabel: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.4,
      textTransform: 'uppercase',
      color: colors.textTertiary,
      marginBottom: 4,
    },
    timelineItem: {
      flexDirection: 'row',
      gap: 10,
      alignItems: 'flex-start',
      paddingTop: spacing.sm,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.borderLight,
    },
    timelineItemFirst: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    timelineBadge: {
      width: 32,
      height: 32,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    timelineBody: { flex: 1, minWidth: 0 },
    timelineRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'baseline',
      gap: spacing.sm,
    },
    timelineAction: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
      flex: 1,
    },
    timelineDetail: {
      fontSize: 13,
      color: colors.textSecondary,
      marginTop: 2,
    },
    timelineDeltaPlus: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.success,
    },
    timelineDeltaMinus: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.error,
    },
    timelineUndo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 6,
      paddingVertical: 4,
      alignSelf: 'flex-start',
    },

    lotList: { gap: spacing.sm },
    lotCard: {
      position: 'relative',
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
      padding: spacing.md,
      gap: 4,
      overflow: 'hidden',
      ...createElevation(colors, 'flat'),
    },
    lotCardArt: {
      position: 'absolute',
      top: 12,
      right: 14,
      opacity: 0.22,
    },
    lotWhen: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
      paddingRight: 48,
    },
    lotWhere: {
      fontSize: 13,
      color: colors.textSecondary,
    },
    lotMore: {
      color: colors.textTertiary,
    },
    lotPack: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
      marginTop: 4,
    },
    lotMeta: {
      fontSize: 13,
      color: colors.textTertiary,
    },
    lotActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: spacing.sm,
      marginTop: 10,
    },
    lotDetailLinks: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 16,
      marginTop: spacing.lg,
    },

    linkish: {
      marginTop: 10,
      paddingVertical: 4,
    },
    linkishText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.primary,
    },

    stickyCta: {
      position: 'absolute',
      left: 12,
      right: 12,
      bottom: 12,
      zIndex: 40,
      borderRadius: radii.xl,
      padding: spacing.sm,
      backgroundColor: colors.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      ...createElevation(colors, 'floating'),
    },

    footerRow: {
      flexDirection: 'row',
      gap: spacing.sm,
    },
    btnPrimary: {
      flex: 1,
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    btnPrimaryDisabled: {
      backgroundColor: colors.gray300,
    },
    btnPrimaryText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.onOlive,
    },
    btnSecondary: {
      flex: 1,
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: spacing.md,
    },
    btnSecondaryText: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    btnGhost: {
      minHeight: Math.min(tapMin, 40),
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: radii.lg,
      alignItems: 'center',
      justifyContent: 'center',
    },
    btnGhostText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    btnSm: {
      flexGrow: 0,
      flexBasis: 'auto',
      paddingHorizontal: 14,
      minWidth: 0,
    },

    buyerChip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: radii.lg,
      backgroundColor: colors.primaryLight,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      minHeight: tapMin,
    },
    buyerChipCopy: { flex: 1, minWidth: 0 },
    buyerChipName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    buyerChange: {
      paddingVertical: 4,
      paddingHorizontal: 8,
    },
    buyerChangeText: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.primary,
    },
    buyerClear: {
      width: 28,
      height: 28,
      borderRadius: 14,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    buyerHint: {
      fontSize: 13,
      color: colors.textTertiary,
      marginBottom: 6,
    },
    buyerList: {
      gap: 4,
      marginVertical: 8,
      maxHeight: 180,
    },
    buyerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
      paddingHorizontal: 10,
      borderRadius: radii.md,
      backgroundColor: colors.surfaceMuted,
      minHeight: Math.min(tapMin, 44),
    },
    buyerRowName: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    buyerRowMeta: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    byGrove: {
      gap: 8,
      marginTop: 4,
    },
    byGroveTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    sectionHint: {
      fontSize: 13,
      color: colors.textTertiary,
      marginBottom: 4,
    },
    groveCard: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
      paddingVertical: 12,
      paddingHorizontal: 12,
    },
    groveCardFocus: {
      borderColor: colors.primary,
      backgroundColor: colors.surfaceMuted,
    },
    groveTitle: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    grovePack: {
      fontSize: 14,
      color: colors.textSecondary,
    },
    groveMeta: {
      fontSize: 12,
      color: colors.textTertiary,
    },
    heroEyebrow: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.6,
      textTransform: 'uppercase',
      color: colors.textTertiary,
    },

    floorHero: {
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingVertical: 16,
      paddingHorizontal: 16,
      gap: 10,
    },
    stockPanel: {
      borderRadius: 12,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      paddingVertical: 14,
      paddingHorizontal: 14,
      gap: 10,
    },
    hairline: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.border,
      alignSelf: 'stretch',
    },
    yearGrid: {
      flexDirection: 'row',
      gap: 12,
    },
    yearCell: {
      flex: 1,
      gap: 2,
    },
    yearLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    yearValue: {
      fontSize: 18,
      fontWeight: '700',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    packTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    packBlock: {
      gap: 2,
    },
    packTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    packName: {
      flex: 1,
      fontSize: 15,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    packFigureRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 12,
    },
    packPieces: {
      fontSize: 14,
      fontWeight: '600',
      color: colors.textSecondary,
      fontVariant: ['tabular-nums'],
    },
    packIndent: {
      paddingLeft: 23,
    },
    packLitres: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    packTotal: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    floorBins: {
      flexDirection: 'row',
      gap: 8,
      marginTop: 4,
    },
    floorBin: {
      flex: 1,
      borderRadius: radii.lg,
      backgroundColor: colors.surfaceMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      paddingVertical: 12,
      paddingHorizontal: 8,
      alignItems: 'center',
      gap: 2,
    },
    floorBinValue: {
      fontSize: 17,
      fontWeight: '800',
      fontVariant: ['tabular-nums'],
      color: colors.textPrimary,
    },
    floorBinLabel: {
      fontSize: 11,
      fontWeight: '650' as '600',
      color: colors.textTertiary,
    },
    floorActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginTop: 8,
    },
    floorActionPrimary: {
      flexGrow: 1,
      flexBasis: '30%',
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      paddingHorizontal: 12,
    },
    floorActionPrimaryText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.onOlive,
    },
    floorActionSecondary: {
      flexGrow: 1,
      flexBasis: '30%',
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      paddingHorizontal: 12,
    },
    floorActionSecondaryText: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.primary,
    },
    floorDoors: {
      gap: 8,
    },
    floorDoor: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      paddingVertical: 12,
      paddingHorizontal: 12,
      ...createElevation(colors, 'flat'),
    },
    floorDoorAlert: {
      borderColor: colors.accentGold,
      backgroundColor: colors.surfaceMuted,
    },
    floorDoorIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surfaceMuted,
    },
    floorDoorTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    floorDoorDetail: {
      fontSize: 13,
      color: colors.textTertiary,
      marginTop: 1,
    },
    floorDoorBadge: {
      minWidth: 22,
      height: 22,
      borderRadius: 11,
      paddingHorizontal: 6,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
    },
    floorDoorBadgeText: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.onOlive,
      fontVariant: ['tabular-nums'],
    },

    ringRow: {
      alignItems: 'center',
      gap: 14,
      marginTop: 6,
    },
    ringWrap: {
      width: 120,
      height: 120,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringCenter: {
      position: 'absolute',
      left: 16,
      right: 16,
      top: 0,
      bottom: 0,
      alignItems: 'center',
      justifyContent: 'center',
    },
    ringCenterValue: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
      textAlign: 'center',
    },
    ringCenterCaption: {
      marginTop: 1,
      fontSize: 11,
      fontWeight: '650' as '600',
      color: colors.textTertiary,
    },
    ringLegend: {
      alignSelf: 'stretch',
      gap: 8,
    },
    ringLegendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    ringDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    ringLegendTop: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 6,
    },
    ringLegendLabel: {
      flex: 1,
      minWidth: 0,
      fontSize: 14,
      fontWeight: '600',
      color: colors.textPrimary,
    },
    ringLegendValue: {
      flexShrink: 0,
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
      textAlign: 'right',
    },
    ringLegendPct: {
      flexShrink: 0,
      width: 58,
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
      fontVariant: ['tabular-nums'],
      textAlign: 'right',
    },

    flowStrip: {
      flexDirection: 'row',
      gap: 8,
    },
    flowCell: {
      flex: 1,
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 10,
      paddingHorizontal: 12,
      gap: 2,
    },
    flowLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    flowValue: {
      fontSize: 16,
      fontWeight: '800',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    formCard: {
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: 14,
      gap: 8,
    },
    formRow: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 12,
    },
    formLabel: {
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textSecondary,
    },
    formValue: {
      fontSize: 15,
      fontWeight: '800',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    verbRow: {
      flexDirection: 'row',
      gap: 8,
    },
    verb: {
      flex: 1,
      minHeight: 76,
      borderRadius: radii.lg,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
      paddingHorizontal: 4,
      paddingVertical: 10,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.oliveBorder,
    },
    verbLabel: {
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
      lineHeight: 15,
      color: colors.textPrimary,
    },

    shelfHead: {
      flexDirection: 'row',
      alignItems: 'baseline',
      justifyContent: 'space-between',
      gap: 8,
    },
    shelfHeadCount: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.textTertiary,
    },
    shelfAll: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 2,
      minHeight: 28,
    },
    shelfAllText: {
      fontSize: 13,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    shelfSummaryTop: {
      flexDirection: 'row',
      alignItems: 'baseline',
      gap: 8,
      marginBottom: 6,
    },
    shelfCard: {
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: 12,
      gap: 8,
    },
    shelfCardTop: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    shelfIcon: {
      width: 28,
      height: 28,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    shelfName: {
      fontSize: 15,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    shelfLitres: {
      fontSize: 14,
      fontWeight: '800',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    shelfPackLine: {
      marginTop: 6,
      fontSize: 12,
      color: colors.textSecondary,
      fontVariant: ['tabular-nums'],
    },
    shelfSeeAll: {
      minHeight: tapMin,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingHorizontal: 12,
    },
    shelfSeeAllText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.primary,
    },
    shelfDetail: {
      borderRadius: radii.lg,
      ...paper,
      padding: 14,
      gap: 8,
    },
    shelfSub: {
      marginTop: 1,
      fontSize: 12,
      color: colors.textTertiary,
    },
    shelfHeadline: {
      fontSize: 18,
      fontWeight: '800',
      letterSpacing: -0.3,
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    shelfSegRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    shelfSegLabel: {
      flex: 1,
      minWidth: 0,
      fontSize: 13,
      color: colors.textSecondary,
    },
    shelfSegValue: {
      fontSize: 13,
      fontWeight: '700',
      color: colors.textPrimary,
      fontVariant: ['tabular-nums'],
    },
    shelfSegPct: {
      width: 48,
      textAlign: 'right',
      fontSize: 12,
      fontWeight: '650' as '600',
      color: colors.textTertiary,
      fontVariant: ['tabular-nums'],
    },
    shelfEdit: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      minHeight: 32,
      paddingHorizontal: 8,
      borderRadius: 999,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface,
    },
    shelfEditText: {
      fontSize: 12,
      fontWeight: '750' as '700',
      color: colors.primary,
    },
    shelfFill: {
      alignSelf: 'flex-start',
      minHeight: 36,
      justifyContent: 'center',
    },
    shelfFillText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.primary,
    },
    shelfScreen: {
      flex: 1,
    },
    shelfTopBar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    shelfBack: {
      width: 40,
      height: 40,
      alignItems: 'center',
      justifyContent: 'center',
    },
    shelfScreenTitle: {
      flex: 1,
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: -0.3,
      color: colors.textPrimary,
    },
    shelfPlus: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      marginRight: 8,
    },
    shelfScreenHint: {
      paddingHorizontal: 16,
      paddingBottom: 12,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },

    whereTitle: {
      fontSize: 22,
      fontWeight: '800',
      letterSpacing: -0.3,
      color: colors.textPrimary,
      marginBottom: 10,
    },
    kindRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
      marginBottom: 10,
    },
    kindChip: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: radii.full,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      minHeight: 36,
      justifyContent: 'center',
    },
    kindChipOn: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    kindChipText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    kindChipTextOn: {
      color: colors.onOlive,
    },
    lensRow: {
      flexDirection: 'row',
      gap: 18,
      marginBottom: 12,
    },
    lensText: {
      fontSize: 14,
      fontWeight: '650' as '600',
      color: colors.textTertiary,
    },
    lensTextOn: {
      fontWeight: '800',
      color: colors.textPrimary,
    },
    whereCard: {
      borderRadius: radii.lg,
      ...paper,
      paddingVertical: 12,
      paddingHorizontal: 12,
      gap: 10,
    },
    whereTop: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    whereIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    whereMeta: {
      marginTop: 2,
      fontSize: 13,
      color: colors.textSecondary,
    },
    whereFoot: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
      marginLeft: 46,
    },
    statusPill: {
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: radii.full,
    },
    statusPillOk: {
      backgroundColor: colors.successLight,
    },
    statusPillWait: {
      backgroundColor: colors.surfaceMuted,
    },
    statusPillText: {
      fontSize: 12,
      fontWeight: '700',
    },
    statusPillTextOk: {
      color: colors.successDark,
    },
    statusPillTextWait: {
      color: colors.textSecondary,
    },
    nudge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 12,
      paddingHorizontal: 14,
      borderRadius: radii.lg,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.accentGold,
    },
    nudgeText: {
      flex: 1,
      fontSize: 14,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    quietLink: {
      minHeight: tapMin,
      alignItems: 'center',
      justifyContent: 'center',
    },
    quietLinkText: {
      fontSize: 14,
      fontWeight: '700',
      color: colors.textTertiary,
    },

    placeCard: {
      borderRadius: radii.lg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.border,
      backgroundColor: colors.surface,
      padding: 12,
      gap: 8,
    },
    placeCardOn: {
      borderColor: colors.primary,
      backgroundColor: colors.primaryLight,
    },
    placeHead: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 10,
    },
    placeTitle: {
      fontSize: 16,
      fontWeight: '700',
      color: colors.textPrimary,
    },
    placeHint: {
      marginTop: 2,
      fontSize: 13,
      lineHeight: 18,
      color: colors.textSecondary,
    },
    placeBody: {
      gap: 8,
      marginTop: 4,
    },
    nameRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    contactIcon: {
      width: tapMin,
      height: tapMin,
      borderRadius: radii.control,
      backgroundColor: colors.primary,
      alignItems: 'center',
      justifyContent: 'center',
    },
    personRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 44,
      paddingHorizontal: 10,
      borderRadius: radii.md,
      backgroundColor: colors.surface,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.borderLight,
    },
    personRowOn: {
      borderColor: colors.primary,
      backgroundColor: colors.surface,
    },
    personName: {
      flex: 1,
      fontSize: 15,
      fontWeight: '650' as '600',
      color: colors.textPrimary,
    },
    savedNote: {
      fontSize: 13,
      fontWeight: '650' as '600',
      color: colors.primary,
    },
  });
}

export type MyOilStyles = ReturnType<typeof createMyOilStyles>;
